prelim_exam: git@github.com:JLRinon-tip/Rinon_PrelimExam.git
username: rinon
writable_chroot: allow_writeable_chroot=YES
ftp_config: "allow_writeable_chroot=YES\npasv_min_port=30000\npasv_max_port=31000\nuserlist_file=/etc/vsftpd/user_list\nuserlist_deny=NO"
ftp:debian: "pasv_enable=Yes\npasv_min_port=10000\npasv_max_port=10100\nallow_writeable_chroot=YES\nssl_tlvs1=YES\nssl_sslv2=NO\nssl_sslv3=NO"
ftp_user: ftpuser
ftp_pass: $mdvr9q5dPLXdBBHO6W4UjM2jkGXBl5Yw8hN5xG8dhTeIlLkfxcXEPQO
naguser_pass: $Zt5WaLpqV74NrxDN5FAGsjQ0RmTjK9ryqlirWvHFszjIUKlPgJlwS0m
nagadmin_pass: rinon
