---
# tasks file for roles/ubuntu-git
- name: create directory
  file:
    path: /home/rinon/repo
    state: directory
    mode: '777'

- name: clone prelim repo
  git:
    repo: 'git@github.com:JLRinon-tip/Rinon_PrelimExam.git'
    dest: /home/rinon/repo
    version: prelim-exam
    clone: yes
    update: yes
